name: 'FoundryVTT Release DB Packer'
description: 'Aids in packing FoundryVTT db files for release.'
author: '@aMediocreDad / Filip Ambrosius'
branding:
  icon: 'code'
  color: 'blue'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  inputdir:
    description: 'The directory containing the json files to pack.'
    required: true
  packsdir:
    description: "The module/system's packs directory."
    required: false
    default: 'packs/'
  pack_nedb:
    description: 'Whether to pack as nedb type db files.'
    required: false
    default: 'false'
