name: "FoundryVTT Release DB Packer"
description: "Aids in packing FoundryVTT db files for release."
author: "@aMediocreDad / Filip Ambrosius"
branding:
  icon: "code"
  color: "blue"
runs:
  using: "node24"
  main: "dist/index.js"
inputs:
  inputdir:
    description: "The directory containing the json files to pack."
    required: true
  packsdir:
    description: "The module/system's packs directory."
    required: false
    default: "packs/"
  remove_input:
    description: "Remove the input directory after packing."
    required: false
    default: "false"
