name: "Action Tests"
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        name: "Lint, Test and Run action"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: "npm"
            - run: npm ci
            - run: npm run build
            - run: npm run lint
            - run: npm test
            - run: npm prune --omit=dev
            - name: Run action
              uses: ./
              with:
                inputdir: "__fixtures__/dummy-json"
                packsdir: "dist"
                pack_nedb: true